Controllers/BookingsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlanesBooking.Models;

namespace PlanesBooking.Controllers
{
    public class BookingsController : Controller
    {
        private readonly MvcDbContext _context;

        public BookingsController(MvcDbContext context)
        {
            _context = context;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            UpdateRelationalData();
            return View(await _context.Bookings.ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookings = await _context.Bookings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookings == null)
            {
                return NotFound();
            }

            return View(bookings);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            UpdateRelationalData();
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BookDate,AirportId,PlaneId,TutorId,Description")] Bookings bookings)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bookings);
                await _context.SaveChangesAsync();
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bookings);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookings = await _context.Bookings.FindAsync(id);
            if (bookings == null)
            {
                return NotFound();
            }
            return View(bookings);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BookDate,AirportId,PlaneId,TutorId,Description")] Bookings bookings)
        {
            if (id != bookings.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookings);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingsExists(bookings.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bookings);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookings = await _context.Bookings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookings == null)
            {
                return NotFound();
            }

            return View(bookings);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bookings = await _context.Bookings.FindAsync(id);
            _context.Bookings.Remove(bookings);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingsExists(int id)
        {
            return _context.Bookings.Any(e => e.Id == id);
        }

        private void UpdateRelationalData()
        {
            ViewData["Airports"] = _context.Airports.ToList();
            ViewData["Planes"] = _context.Planes.ToList();
            ViewData["Tutors"] = _context.Tutors.ToList();
        }
    }
}

Controllers/PlanesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlanesBooking.Models;

namespace PlanesBooking.Controllers
{
    public class PlanesController : Controller
    {
        private readonly MvcDbContext _context;

        public PlanesController(MvcDbContext context)
        {
            _context = context;
        }

        // GET: Planes
        public async Task<IActionResult> Index()
        {
            UpdateAirports();
            return View(await _context.Planes.ToListAsync());
        }

        // GET: Planes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planes = await _context.Planes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (planes == null)
            {
                return NotFound();
            }

            return View(planes);
        }

        // GET: Planes/Create
        public IActionResult Create()
        {
            UpdateAirports();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,AirportId")] Planes planes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(planes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(planes);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planes = await _context.Planes.FindAsync(id);
            if (planes == null)
            {
                return NotFound();
            }
            UpdateAirports();
            return View(planes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,AirportId")] Planes planes)
        {
            if (id != planes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(planes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanesExists(planes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(planes);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planes = await _context.Planes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (planes == null)
            {
                return NotFound();
            }

            return View(planes);
        }

        // POST: Planes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var planes = await _context.Planes.FindAsync(id);
            _context.Planes.Remove(planes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlanesExists(int id)
        {
            return _context.Planes.Any(e => e.Id == id);
        }

        private void UpdateAirports()
        {
            ViewData["Airports"] = _context.Airports.ToList();
        }
    }
}

Controllers/TutorsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlanesBooking.Models;

namespace PlanesBooking.Controllers
{
    public class TutorsController : Controller
    {
        private readonly MvcDbContext _context;

        public TutorsController(MvcDbContext context)
        {
            _context = context;
        }

        // GET: Tutors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tutors.ToListAsync());
        }

        // GET: Tutors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tutors = await _context.Tutors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tutors == null)
            {
                return NotFound();
            }

            return View(tutors);
        }

        // GET: Tutors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tutors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Nationality,Gender,Birthday")] Tutors tutors)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tutors);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tutors);
        }

        // GET: Tutors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tutors = await _context.Tutors.FindAsync(id);
            if (tutors == null)
            {
                return NotFound();
            }
            return View(tutors);
        }

        // POST: Tutors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Nationality,Gender,Birthday")] Tutors tutors)
        {
            if (id != tutors.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tutors);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TutorsExists(tutors.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tutors);
        }

        // GET: Tutors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tutors = await _context.Tutors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tutors == null)
            {
                return NotFound();
            }

            return View(tutors);
        }

        // POST: Tutors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tutors = await _context.Tutors.FindAsync(id);
            _context.Tutors.Remove(tutors);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TutorsExists(int id)
        {
            return _context.Tutors.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlanesBooking</title>
    <link rel="stylesheet" href="~/css/foundation.css">
    <link rel="stylesheet" href="~/css/app.css">
    <link rel="stylesheet" href="~/css/homelayout.css">
    <!-- <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlanesBooking.styles.css" asp-append-version="true" />
</head>
<body>
    <!--<header>
        <nav class="title-bar">
            <div class="top-bar-left">
                    <ul class="dropdown menu">
                         <li><a asp-area="" asp-controller="Home" asp-action="Index">PlanesBooking</a></li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Airports" asp-action="Index">Airports</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planes" asp-action="Index">Planes</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tutors" asp-action="Index">Tutors</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Index">Bookings</a>
                        </li>
                    </ul>
            </div>
        </nav>
    </header>-->
    <div class="grid-container fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            <p>2022 - Planes Booking App </p>
            <p>All rights reserved</p>
        </div>
    </footer> 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/vendor/what-input.js"></script>
    <script src="~/js/vendor/foundation.js"></script>
    <!-- <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>-->
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlanesBooking</title>
    <link rel="stylesheet" href="~/css/foundation.css">
    <link rel="stylesheet" href="~/css/app.css">
    <!-- <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlanesBooking.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="top-bar">
            <div class="top-bar-left">
                    <ul class="dropdown menu">
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Index">Bookings</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Airports" asp-action="Index">Airports</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planes" asp-action="Index">Planes</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tutors" asp-action="Index">Tutors</a>
                        </li>
                        
                    </ul>
            </div>
            <div class="top-bar-right">
                <ul class="menu">
                    <li>
                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="grid-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PlanesBooking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/vendor/what-input.js"></script>
    <script src="~/js/vendor/foundation.js"></script>
    <!-- <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>-->
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>